name: fireducks-blogathon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.0.3
  - jupyterlab=4.0.0
  - pip=23.1.2
  - polars=0.19.0
  - modin=0.23.0
  - pip:
    - fireducks==1.2.0